#
# Makefile to build a bootable disk
#

BUILD = ..

DSK_IMG = disk.img
DSK_SIZ = 100M
DSK_MBR = mbr.bin

PROM = $(BUILD)/prom/boot.mem

all:		$(DSK_IMG)

run-0:		$(DSK_IMG)
		$(BUILD)/bin/sim -i -p $(PROM) -s 000 -d $(DSK_IMG)

run-1:
		$(BUILD)/bin/sim -i -p $(PROM) -s 001

$(DSK_IMG):
		$(BUILD)/bin/mkdisk $(DSK_IMG) $(DSK_SIZ)
		dd if=$(DSK_MBR) of=$(DSK_IMG) bs=512 count=1 conv=notrunc

clean:
		rm -f *~ $(DSK_IMG)
		rm -f serial.dev
